### ISSUE TITLE
Posting data to SDC HTTP server url from javascript throwsCORS issue

### ISSUE THREAD

**Issue by nishutayal** [streamsets/ansible-datacollector-sample-playbook#2]
Hi, I am using Streamset pipeline for streaming data from browsers. So for that, I created a pipeline with HTTP server origin to post data from browsers Javascript and tried to write in that URL using REST client, and it writes successfully.  Response Headers are already set in the SDC.properties file.  

```
http.access.control.allow.origin=*
http.access.control.allow.headers=origin, content-type, accept, authorization, x-requested-by, x-ss-user-auth-token, x-ss-rest-call
http.access.control.allow.methods=GET, POST, PUT, DELETE, OPTIONS, HEAD
```

But when I try to write some data from JavaScript using XMLHTTPRequest, it throws error for pre-flight request. Below is the JavaScript code: 

      var http = new XMLHttpRequest();
      var value = '{ "prop1": "value 2", "prop2": "value 2" }';
      var url ='http://13.68.93.97:8100/'
      var async = true
	 if ('withCredentials' in http) {
		http.open('OPTIONS', url, async);
	} else if (typeof XDomainRequest != "undefined") {
		http = new XDomainRequest(); //for IE
		http.open('OPTIONS', url);
	} else {
		http.open('OPTIONS', url, async);
	}
        http.open('POST', url, true);
        http.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
        http.setRequestHeader('X-SDC-APPLICATION-ID', 'testApp1');
        // Below headers are set in sdc.properties, so doesn't make any difference in javascript
	http.setRequestHeader("Access-Control-Allow-Origin", "*");
	http.setRequestHeader('Access-Control-Allow-Methods', "POST, OPTIONS, GET");
	http.setRequestHeader('Access-Control-Allow-Credentials', "true");
	http.setRequestHeader('Access-Control-Expose-Headers', "X-Region");
	http.setRequestHeader("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept,Accept-language");
	http.withCredentials = true;
    http.onreadystatechange = function () {
        if (http.readyState == 4 && http.status == 200) {
            console.log(http.responseText);
        }
    }
    http.send(value); 

Error thrown from the above code execution :

> XMLHttpRequest cannot load http://13.68.93.97:8100/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

Any help will be really helpful. Thanks..!!

**Comment by kunickiaj** [comment]
Hi, this github repo is for the ansible playbook for SDC deployment. General SDC questions should be directed to the various community channels (user list, slack, JIRA) available here: https://streamsets.com/community/
